"""ExecutorAgent: produce a concrete change set (file edits + PR + Jira comment).

When OpenAI is configured, the LLM drives this. Otherwise the deterministic
fallback produces a plausible change set so the demo works end to end.
"""
from __future__ import annotations

import re
from typing import Any

from app.agents.base import AgentInput, AgentType, BaseAgent
from app.prompts import EXECUTOR_PROMPT, EXECUTOR_SCHEMA


def _slugify(value: str, *, max_len: int = 40) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.lower()).strip("-")
    return (slug or "task")[:max_len]


class ExecutorAgent(BaseAgent):
    agent_type = AgentType.EXECUTOR
    agent_name = "ExecutorAgent"
    system_prompt = EXECUTOR_PROMPT
    output_schema_hint = EXECUTOR_SCHEMA

    def fallback_output(self, agent_input: AgentInput) -> dict[str, Any]:
        task = agent_input.task or {}
        subset = agent_input.project_data_subset or {}
        title = task.get("title") or "Task"
        description = task.get("description") or ""
        task_key = task.get("key") or task.get("id") or "TASK"

        # Pick a sensible target service based on task labels/title first,
        # then fall back to any hint passed via the focused subset.
        inferred = self._infer_target_service(task, subset)
        target = inferred or subset.get("target") or "payments-service"
        branch_name = f"mycelium/{task_key}-{_slugify(title)}"
        doc_path = f"docs/onboarding/{target}.md"

        # Compose the onboarding doc content.
        doc_content = self._build_onboarding_doc(target, title, description, subset)

        pr_description = (
            f"## Summary\n"
            f"Autonomous change generated by **Mycelium** for Jira **{task_key}**.\n\n"
            f"> {title}\n\n"
            f"## Scope\n"
            f"- Adds `{doc_path}` covering architecture, code map, ownership, "
            "runbooks, and FAQ for the service.\n"
            f"- No existing files were modified.\n\n"
            f"## Context sources\n"
            f"- Jira ticket {task_key}\n"
            f"- Repo file references in project_data\n"
            f"- Uploaded transcripts + docs\n\n"
            f"## Human review\n"
            f"- Please confirm the code map section matches current service layout.\n"
            f"- Please confirm ownership + on-call references are up to date.\n"
        )

        jira_comment = (
            f"Mycelium finished a first pass on {task_key}.\n\n"
            f"Pull request: {{PR_URL}}\n\n"
            f"Adds {doc_path}. Please review when you have a moment."
        )

        return {
            "action_taken": "open_pull_request",
            "summary": (
                f"Drafted an onboarding doc for {target} at {doc_path} on branch "
                f"{branch_name}."
            ),
            "file_changes": [
                {
                    "path": doc_path,
                    "operation": "create",
                    "content": doc_content,
                    "description": f"Onboarding guide for {target}.",
                }
            ],
            "pr": {
                "title": f"{task_key}: {title}",
                "description": pr_description,
                "branch_name": branch_name,
                "base_branch": "main",
            },
            "jira_comment": jira_comment,
            "safety_notes": (
                "Only creates one new doc. No existing files modified. PR is opened "
                "for human review — never auto-merged."
            ),
            "requires_real_integration": False,
        }

    # ---------------------------------------------------------------
    # Helpers
    # ---------------------------------------------------------------

    @staticmethod
    def _infer_target_service(
        task: dict[str, Any], subset: dict[str, Any]
    ) -> str | None:
        text = " ".join(
            [
                str(task.get("title") or ""),
                str(task.get("description") or ""),
                " ".join(task.get("labels") or []),
            ]
        )
        match = re.search(r"\b([\w-]+)-service\b", text)
        if match:
            return match.group(0)
        repos = subset.get("github_repositories") or []
        if repos and isinstance(repos, list):
            first = repos[0]
            if isinstance(first, dict) and first.get("name"):
                return str(first["name"])
        return None

    @staticmethod
    def _build_onboarding_doc(
        target: str, title: str, description: str, subset: dict[str, Any]
    ) -> str:
        code_files = subset.get("code_files") or []
        code_lines = [
            f"- `{f.get('path')}` — {f.get('summary') or ''}".rstrip(" —")
            for f in code_files
            if isinstance(f, dict) and f.get("path")
        ][:10] or ["- _No repo files were supplied in project_data._"]
        doc_sources = subset.get("docs") or []
        sources = [
            f"- {d.get('title')}"
            for d in doc_sources
            if isinstance(d, dict) and d.get("title")
        ] or ["- _No docs supplied in project_data._"]
        return (
            f"# {target} — Onboarding\n\n"
            f"_Autogenerated by Mycelium for task: {title}._\n\n"
            f"## What it does\n{description or 'See service description.'}\n\n"
            f"## Architecture\n"
            f"- API entrypoint → service layer → adapters.\n"
            f"- See source files below for the current layout.\n\n"
            f"## Code map\n" + "\n".join(code_lines) + "\n\n"
            f"## Ownership\n- Primary team: TODO (fill in during review)\n"
            f"- On-call: PagerDuty rota (link TBD)\n\n"
            f"## Runbooks\n- TODO: link to the service runbook.\n\n"
            f"## FAQ\n- **How do I run it locally?** TODO.\n"
            f"- **Where do deploys go?** TODO.\n\n"
            f"## Sources used\n" + "\n".join(sources) + "\n"
        )
