"""Prompt constants for every agent.

Keeping prompts in their own module:
- avoids 1000-line agent files,
- makes prompts diff-reviewable,
- allows reuse across tests and demos.
"""

from app.prompts.agents import (
    CODEBASE_ANALYST_PROMPT,
    CODEBASE_ANALYST_SCHEMA,
    DOCS_ANALYST_PROMPT,
    DOCS_ANALYST_SCHEMA,
    EXECUTOR_PROMPT,
    EXECUTOR_SCHEMA,
    JIRA_ANALYST_PROMPT,
    JIRA_ANALYST_SCHEMA,
    ORCHESTRATOR_PROMPT,
    ORCHESTRATOR_SCHEMA,
    PLANNER_PROMPT,
    PLANNER_SCHEMA,
    REVIEWER_PROMPT,
    REVIEWER_SCHEMA,
    RISK_SAFETY_PROMPT,
    RISK_SAFETY_SCHEMA,
    TRANSCRIPT_ANALYST_PROMPT,
    TRANSCRIPT_ANALYST_SCHEMA,
)

__all__ = [
    "CODEBASE_ANALYST_PROMPT",
    "CODEBASE_ANALYST_SCHEMA",
    "DOCS_ANALYST_PROMPT",
    "DOCS_ANALYST_SCHEMA",
    "EXECUTOR_PROMPT",
    "EXECUTOR_SCHEMA",
    "JIRA_ANALYST_PROMPT",
    "JIRA_ANALYST_SCHEMA",
    "ORCHESTRATOR_PROMPT",
    "ORCHESTRATOR_SCHEMA",
    "PLANNER_PROMPT",
    "PLANNER_SCHEMA",
    "REVIEWER_PROMPT",
    "REVIEWER_SCHEMA",
    "RISK_SAFETY_PROMPT",
    "RISK_SAFETY_SCHEMA",
    "TRANSCRIPT_ANALYST_PROMPT",
    "TRANSCRIPT_ANALYST_SCHEMA",
]
